- name: Stop and disable the apparmor service
  ansible.builtin.service:
    name: apparmor
    enabled: no
    state: stopped

- name: Stop and disable the firwall service
  ansible.builtin.service:
    name: ufw
    enabled: no
    state: stopped

    