---
 - hosts: 127.0.0.1
   connection: local
   become: yes
#   roles: 
#     - workers
   tasks:
    - name: "Applying roles {{ roles }}"
      include_role:
        name: "{{ role_name }}"
      with_items: 
        - "{{ roles }}"
      loop_control:
        loop_var: role_name