- name: "Create MySQL directory for Rancher Server"
  file:
    path: /rancher_mysql
    state: directory

- name: "Run Rancher Server container"
  docker_container:
    name: ranchersvr
    image: rancher/server:v1.0.2
    state: present
    volumes:
    - /rancher_mysql:/var/lib/mysql
    restart_policy: always
    ports:
    - 8080

# sudo mkdir /rancher_mysql
# sudo docker run -d -v /rancher_mysql:/var/lib/mysql --restart=always -p 8080:8080 rancher/server:v1.0.2
