- name: "Create MySQL directory for Rancher Server"
  file:
    path: /rancher_mysql
    state: directory

- name: "Run Rancher Server container"
  docker_container:
    name: ranchersvr
    image: rancher/rancher:v2.6.1
    state: started
    volumes:
    - /rancher_mysql:/var/lib/mysql
    restart_policy: always
    privileged: yes
    exposed_ports:
    - "80"
    - "443"
    published_ports:
    - "443:443"
    - "80:80"

# sudo mkdir /rancher_mysql
# sudo docker run -d -v /rancher_mysql:/var/lib/mysql --restart=always -p 8080:8080 rancher/server:v1.0.2
