- name: install docker
  apt:
          state: latest
          pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - docker.io
- name: Install Docker Module for Python
  pip:
    name: docker
- name: start docker
  service:
          name: docker
          state: started
