- apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
- apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
          state: latest
          pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python-docker
- name: start docker
  service:
          name: docker
          state: started
