---
 - hosts: 127.0.0.1
   connection: local
   become: yes
#   roles: 
#     - workers
   tasks:
    - name: "Applying role {{ role }}"
      import_role:
        name: "{{ item }}"
      with_item: "{{ roles }}"