# GSUtil Installation
# echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
# sudo apt-get install apt-transport-https ca-certificates gnupg

- name: "Install common prerequisites"
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - gnupg
    state: present 

- apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
- apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present


# This section is the CLI installation for bmctl
# > mkdir baremetal
# > cd baremetal
# > gsutil cp gs://anthos-baremetal-release/bmctl/1.7.0/linux-amd64/bmctl .
# > chmod a+x bmctl
# > mv bmctl /usr/local/sbin
